CREATE TABLE TIPO (
	CODIGO SERIAL,
	NOME VARCHAR(50),
	CONSTRAINT PK_CODIGO PRIMARY KEY (CODIGO)
);

INSERT INTO TIPO(NOME) VALUES ('LIMPEZA');
INSERT INTO TIPO(NOME) VALUES ('HIGIENE');
INSERT INTO TIPO(NOME) VALUES ('LATICÍNIO');
INSERT INTO TIPO(NOME) VALUES ('FARINÁCEOS');
INSERT INTO TIPO(NOME) VALUES ('FRUTAS');
INSERT INTO TIPO(NOME) VALUES ('VERDURAS');
INSERT INTO TIPO(NOME) VALUES ('AUTOMOTIVOS');
DELETE FROM TIPO WHERE (NOME='AUTOMOTIVOS');
SELECT * FROM TIPO;

CREATE TABLE PRODUTO (
	CODP SERIAL,
	CODT INT,
	NOME VARCHAR(50),
	VALOR INT,
	CONSTRAINT PK_CODP PRIMARY KEY (CODP),
	CONSTRAINT FK_CODT FOREIGN KEY (CODT) REFERENCES TIPO(CODIGO)
);

INSERT INTO PRODUTO (nome,valor,codt) VALUES ('SABAO',10,1);
INSERT INTO PRODUTO (nome,valor,codt) VALUES ('DETERGENTE',2,1);
INSERT INTO PRODUTO (nome,valor,codt) VALUES ('AGUA SANITARIA',4,1);
INSERT INTO PRODUTO (nome,valor,codt) VALUES ('ALCOOL',8,1);

INSERT INTO PRODUTO (nome,valor,codt) VALUES ('XAMPU',22,2);
INSERT INTO PRODUTO (nome,valor,codt) VALUES ('HIDRADANTE',15,2);
INSERT INTO PRODUTO (nome,valor,codt) VALUES ('CREME DENTAL',8,2);

INSERT INTO PRODUTO (nome,valor,codt) VALUES ('LEITE',5,3);
INSERT INTO PRODUTO (nome,valor,codt) VALUES ('QUEIJO',8,3);
INSERT INTO PRODUTO (nome,valor,codt) VALUES ('REQUEIJAO',5,3);

INSERT INTO PRODUTO (nome,valor,codt) VALUES ('BOLACHA',4,4);
INSERT INTO PRODUTO (nome,valor,codt) VALUES ('BISCOITO',3,4);
INSERT INTO PRODUTO (nome,valor,codt) VALUES ('PAO',8,4);

INSERT INTO PRODUTO (nome,valor,codt) VALUES ('BANANA',2,5);
INSERT INTO PRODUTO (nome,valor,codt) VALUES ('MACA',6,5);
INSERT INTO PRODUTO (nome,valor,codt) VALUES ('UVA',13,5);
INSERT INTO PRODUTO (nome,valor,codt) VALUES ('LARANJA',8,5);
INSERT INTO PRODUTO (nome,valor,codt) VALUES ('GOIABA',6,5);

INSERT INTO PRODUTO (nome,valor,codt) VALUES ('ALFACE',4,6);
INSERT INTO PRODUTO (nome,valor,codt) VALUES ('BROCOLIS',3,6);
INSERT INTO PRODUTO (nome,valor,codt) VALUES ('COUVE',3,6);
INSERT INTO PRODUTO (nome,valor,codt) VALUES ('ABOBORA',10,6);

ALTER TABLE TIPO ADD CONSTRAINT UK_NOME UNIQUE (NOME);

SELECT * FROM TIPO, PRODUTO WHERE (PRODUTO.CODT = TIPO.CODIGO);

SELECT CODP, NOME, VALOR, ((VALOR*(1.1)) AS NOVO FROM PRODUTO WHERE CODT = 4;
						 
UPDATE PRODUTO SET VALOR=((VALOR*1.1)) WHERE CODT = 4;
						   SELECT * FROM PRODUTO;
CREATE TABLE CLIENTE (
NOME VARCHAR(50),
TEL CHAR(11),
CODC SERIAL,
CONSTRAINT PKCLIENTE PRIMARY KEY (CODC)
);
			
CREATE TABLE NF (
CODNF SERIAL,
DESCRICAO VARCHAR(200),
DATANF DATE,
CODC INT,
CONSTRAINT PKNF PRIMARY KEY (CODNF),
CONSTRAINT FKCLIENTE FOREIGN KEY (CODC) REFERENCES CLIENTE(CODC)
);
						   
CREATE TABLE ITENS(
	CODCIT INT,
	CODNFIT INT,
	QTE INT,
	CONSTRAINT FKCLIENTEIT FOREIGN KEY (CODCIT) REFERENCES CLIENTE(CODC),
	CONSTRAINT FKNFIT FOREIGN KEY (CODNFIT) REFERENCES NF(CODNF),
	CONSTRAINT PKITENS PRIMARY KEY (CODNFIT, CODCIT)
)